### ISSUE TITLE
If player attacks enemy, then enemy should detect player

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#176]
Currently if you are not "perceived" by an enemy, They remain in their idles. The Zakobon and others should wander around by default IMO, but this in particular should be noted, that when you fire on them and the haven't detected you yet, they will still and not detect you. Thus making it very easy to kill them. I know we have lots of plans to make the AI better and this was probably on the docket, but I wanted to track it as an issue.

**Comment by DamnedNForsaken** [comment]
This was addressed in a PR or two ago i think. But yeah can you verify this is solved @JJChalupnik

**Comment by JJChalupnik** [comment]
This is still an issue. In the opening hallways, go to the door that leads to the computer mainframe room, and fire at the last two Zakobon down that hall. They will just get hit, and not detect Megaman. They also don't wander around by default. We should probably have a flag that enables/disables this behavior on spawn. Thoughts?

**Comment by DamnedNForsaken** [comment]
We have talked on this quite a bit, i believe that this PR finally fixes the issue:
https://github.com/DamnedNForsaken/MMLX/pull/227
Going to close
